name: Release Runner

on:
  workflow_dispatch:
  push:

jobs: 
  tag:
    name: Generate next tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Dump github context
        run: echo "$GITHUB_CONTEXT"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: Check version
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const tags = await github.rest.repos.listTags({
              owner: '${{ github.event.repository.owner.name }}',
              repo: '${{ github.event.repository.name }}'
            })
            console.log(tags)
        
  build:
    needs: tag
    strategy: 
      matrix:
        runtime: [win-x64, win-arm64]
        include:
          - runtime: win-x64
            os: windows-2019
          - runtime: win-arm64
            os: windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Build
        run: echo build
        
      - name: Package
        run: echo package
        
      - name: Upload Artifact
        run: echo upload
        
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  
  publish-image:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4